"use client";
import { useEffect, useMemo, useState } from "react";

type AuditEntry = { id: string; source: string; createdAt: string; action: string; entityType: string; entityId: string; summary: string; payload?: unknown; actorUser?: { id: string; name: string; email?: string | null } | null; };
function formatDateTime(iso: string) { return new Date(iso).toLocaleString("fr-FR", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" }); }
export default function AuditClient({ defaultCompanyId, isGlobalSupport }: { defaultCompanyId: string; isGlobalSupport: boolean; }) {
  const [companyId, setCompanyId] = useState(defaultCompanyId);
  const [entityType, setEntityType] = useState("");
  const [entityId, setEntityId] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [entries, setEntries] = useState<AuditEntry[]>([]);
  const query = useMemo(() => { const p = new URLSearchParams(); if (companyId) p.set("companyId", companyId); if (entityType) p.set("entityType", entityType); if (entityId) p.set("entityId", entityId); p.set("limit", "100"); return p.toString(); }, [companyId, entityId, entityType]);
  useEffect(() => { let cancelled=false; async function load(){ if(!companyId) return; setLoading(true); setError(null); try{ const res=await fetch(`/api/audit?${query}`); const json=await res.json().catch(()=>null); if(!res.ok||!json||json.ok!==true) throw new Error(typeof json?.error==='string'?json.error:`HTTP_${res.status}`); if(!cancelled) setEntries(Array.isArray(json.data?.entries)?json.data.entries:[]);}catch(err){ if(!cancelled){ setEntries([]); setError(err instanceof Error?err.message:'Erreur inconnue');}} finally { if(!cancelled) setLoading(false);} } void load(); return ()=>{cancelled=true}; }, [companyId, query]);
  return (<section style={{ display: "grid", gap: 12 }}><div style={{ display: "grid", gap: 8, gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))" }}><input value={companyId} onChange={(e)=>setCompanyId(e.target.value)} placeholder="companyId" disabled={!isGlobalSupport} /><input value={entityType} onChange={(e)=>setEntityType(e.target.value)} placeholder="entityType (optionnel)" /><input value={entityId} onChange={(e)=>setEntityId(e.target.value)} placeholder="entityId (optionnel)" /></div>{loading && <div>Chargement de l&apos;audit…</div>}{error && <div style={{ color: 'crimson' }}>Erreur : {error}</div>}{!loading && !error && entries.length===0 && <div style={{ opacity: 0.75 }}>Aucune entrée d&apos;audit.</div>}<div style={{ display: 'grid', gap: 10 }}>{entries.map((entry)=><div key={`${entry.source}-${entry.id}`} style={{ border:'1px solid rgba(255,255,255,0.14)', borderRadius:12, padding:12 }}><div style={{ display:'flex', justifyContent:'space-between', gap:12, flexWrap:'wrap' }}><div style={{ fontWeight:800 }}>{entry.summary}</div><div style={{ opacity:0.75 }}>{formatDateTime(entry.createdAt)}</div></div><div style={{ marginTop:6, opacity:0.85 }}>{entry.source} • {entry.action} • {entry.entityType} • {entry.entityId}</div><div style={{ marginTop:6, opacity:0.8 }}>Acteur : {entry.actorUser?.name ?? 'Système'}</div>{entry.payload !== undefined && <pre style={{ whiteSpace:'pre-wrap', marginTop:8, fontSize:12, opacity:0.9 }}>{JSON.stringify(entry.payload, null, 2)}</pre>}</div>)}</div></section>);
}
